### ISSUE TITLE
Integrate w/ a Human API

### ISSUE THREAD

**Issue by tejasmanohar** [tejasmanohar/old-site#2]
What if I wrote a Human API to analyze what I was doing and provide public data? Endpoints could include what I'm reading, listening to, eating, walking patterns, etc... could be linked w/ Pebble, smartphone, and computer.

https://github.com/tejasmanohar/website/issues/1

**Comment by macalinao** [comment]
I would like that. I want to know everything about you all the time.

:trollface:

**Comment by tejasmanohar** [comment]
K then
